### ISSUE TITLE
Add colours to the output

### ISSUE THREAD

**Issue by 7phalange7** [lordlabuckdas/gtfoo#3]
Most of the output is in the default colour right now.
### Format the colour of different sections of the output, according to the [color palette](https://github.com/lordlabuckdas/gtfoo##color-scheme) provided in the `README` .

**Comment by alphaX86** [comment]
I'll take this issue and format the colors. May I??

**Comment by 7phalange7** [comment]
> 
> 
> I'll take this issue and format the colors. May I?? @lordlabuckdas

Yeah go ahead 👍

**Comment by alphaX86** [comment]
> > I'll take this issue and format the colors. May I?? @lordlabuckdas
> 
> Yeah go ahead 👍 . Also join the discord server mentioned in the readme

Sure! 👍
