### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Tejas1510** [lordlabuckdas/gtfoo#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The project is currently missing the Code of Conduct file which is important for open source project
So can I go for it @lordlabuckdas 

**Describe alternatives you've considered**

**Additional context**

**Comment by 7phalange7** [comment]
You can go for it @Tejas1510.

**Comment by lordlabuckdas** [comment]
fixed in #33; closing
